<?

function Encabezado (){
	echo '<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
    <link rel="stylesheet" type="text/css" href="General.css" media="screen" />
    
</head>
<title></title>
    <body><center>
        <div class="logo">
            <img class="img_logo" src="Logo.jpg">
        </div>  
    </center>
    <div class="text">
            Bueno, bonito, barato
        </div>
        <br>
<div class="general">';
}

function Cierre (){
    echo "
</div> 
<br> 
<div style='background-color: #7FFFD4; font-family: Verdana;'>
    P&aacute;gina creada por Adrián, Javier y Pablo.
    Tel&eacute;efono de contacto: 962 225 761
</div>
</body>
</html>
	";
}










?>